#!/usr/bin/env bash

CACHES=$(gh actions-cache list --limit=100 | cut -f1)

for cache in $CACHES; do
    echo "Removing cache $cache..."
    gh actions-cache delete --confirm $cache

    sleep 5
done
